- fabio-src/cbfimage.py
Skips the MD5 check if the checksum is not available in the header.
> Quick fix for #25

- fabio-src/tifimage.py
The tostring() method has been removed on Pillow. This PR fixes the issue #44.
> FIX: tostring() on conversion from Image to numpy array

- scripts/fabio_viewer
Without that, i still have conflict on my Debian 8 distribution.
I guess it tries to provide a simulated Qt4 api from a Qt5 one.
```
valls@marie:~$ fabio_viewer workspace/data/Pilatus1M/Pilatus1M.edf 
Traceback (most recent call last):
File "/usr/local/bin/fabio_viewer", line 42, in <module>
from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg as FigureCanvas
File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_qt4agg.py", line 18, in <module>
from .backend_qt5agg import FigureCanvasQTAggBase as _FigureCanvasQTAggBase
File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5agg.py", line 15, in <module>
from .backend_qt5 import QtCore
File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5.py", line 27, in <module> …
```
> Force to use Qt4

- setup.py
- The project do not use it, and it is not available on setuptools
- As result there was an import error and setuptools was not used
- Now setuptools is fully imported
> Remove install_data

- fabio/edfimage.py
- fabio/fabioimage.py
This patch add robustness on EdfImage constructor
It contains
- A refactoring to be sure the super constructor is always called
- It take care of the case where dim==0 and raise an exception
- The last patch avoid using array bigger than 2d (before that, the input data was not fully used). We can remove it if you think it is safer for compatibility.
> Fix edf constructor

- fabio/ext/include/ccp4_pack.h
Use default stdint.h with MSVC++ 14.0: closes #104
> Fix build on Windows for python3.6-64 bits

- fabio/OXDimage.py
- fabio/test/testOXDimage.py
- Ascii header size is now fixed for sapphire 4.0 header (it can be a regression)
- Fix header reading for sapphire 4.0 header (it was also wrong for our testfile)
- Fix read and write of alpha/beta angles
- Add Pilatus300k detector type (detector type 5 and 6 are still missing)
- Add a new test file `pilatus300k.rod_img` provided by @Niolon
> Fix OXD for pilatus300k

- fabio/edfimage.py
- fabio/fabioimage.py
`edfimage.next` raises `ValueError` when reaching the end of a multiframe EDF that `fabioimage.__iter__` didn't catch.
Still, `edfimage.getframe` will log an error right before raising the `ValueError` exception.
Closes #109
> Fix end of iteration for multiframe single EDF file

- fabio/fabioformats.py
- fabio/jpeg2kimage.py
- fabio/openimage.py
- fabio/test/testjpeg2kimage.py
- run_tests.py
The connector is supporting 2 decoders (PIL and glymur).
- PIL on debian 8 is not able to load JPG2000.
- The current glymur is not working with python file object. I tried to update the glymur API to make the result better, but right now our connector is very hackish. But i test it on all release version of the branch 0.8.x
- I upload 2 small files on www.silx.org (uint8 and uint16). Other formats are not supported.
Closes #120
> Support JPEG 2000 format

- fabio/fabioimage.py
- fabio/openimage.py
- fabio/test/test_all.py
- fabio/test/test_failing_files.py
- Use with to open file for a short period of time
- Also clean up logs
- Clean up exception to only raise `IOError`
Closes #167
> Fix close with failing files

- fabio/compression.py
- fabio/edfimage.py
- fabio/fabioimage.py
- fabio/test/test_failing_files.py
- fabio/test/testedfimage.py
This PR will try to improve reading multiframe EDF containing many GZ blocks.
- Create unittest to test bad files containing incomplete frames
- Create unittest to test bad files containing incomplete frames with GZ blocks
- Clean up the parsing of the headers
- Remove `measure_size` which occurs slow down when reading files using a lot of GZ blocks in Python2
- Add API to know if file is incomplete or frame is incomplete (maybe we can use another API: `is_valid` or thing like that)
- Allow to read part of file using incomplete GZ blocks (the last one)
- Remove some `replace`
- Empty edf or containing a single frame with bad header raises now an `IOError`
Relative to https://github.com/silx-kit/silx/issues/1168
Testing massively compressed files from ID01 using Python2, the result is fine …
> Improve EDF reader

- fabio/__init__.py
- fabio/test/test_all.py
- fabio/test/test_formats.py
This PR create an empty function `fabio.register` for the release of fabio 0.6. It allow people to patch there code before the change the coming change of the behaviour in fabio 0.7.
That's just a proposal in case we do not apply the change now.
> Proposal for fabio.register function before introducing the change

- fabio/openimage.py
This will facilitate opening New Bruker (bruker100) format frames.
> add magic number for  Bruker100 images

- fabio/edfimage.py
- fabio/test/testedfimage.py
This PR fix an issue introducing a wrong parsing of the very first key of EDF files. It also provide tests to check deeper the file header on our test samples in order to prevent further regressions.
> Fix EDF header parsing

- fabio/edfimage.py
If you (only) remove some reserved header (ex DIM_1) from a edf image, when you write this image an exception is raised: KeyError: u'Dim_1'
> EDF: clear capsHeader before update it

- README.rst
The [package page on PyPI](https://pypi.python.org/pypi/fabio) currently shows the raw rst markup, which looks especially ugly when it's not in a monospace font. When the rst is valid, it shows as nicely rendered HTML instead.
I used the [readme package](https://pypi.python.org/pypi/readme) to find the changes needed.
> Fix rst README for PyPI

- fabio/edfimage.py
- fabio/test/testedfimage.py
- Remove self.capsHeadcer
- Create and use it only locally when reading/writing EDF headers
- Remove the `capsHeader` API
> Clean up capsheader from EDF

- ci/appveyor.yml
- run_tests.py
- Fix `--no-cache-dir --no-index` on pip
- Only test the project 1 time on appveyor (it's the same as travis), instead of 4 times
- Backport grouping skipped test reason from silx
> Improve CI scripts

- fabio/openimage.py
- URL is never used
- Fix regression with absolute Windows path using slash instead of backslash + dataset path `"C:/something.h5::group/entry"`
Work around:
- Use relative path
Closes  #238
> Remove URL from openimage

- fabio/__init__.py
- fabio/app/convert.py
- fabio/fabioformats.py
- fabio/fabioimage.py
- fabio/fabioutils.py
- fabio/openimage.py
- fabio/test/test_formats.py
- Explicit registration of the available codecs
- Remove `registry` from `fabioimage.FabioImage` and move it to `fabioformats`
- Remove the FabioImage metaclass
- Test for the `fabio.register` function (check if adding a new format at runtime is working)
- Deprecate `FabioImage.factory`
It changes the behavior for people who are registering custom formats (now you have to call explicitly `fabio.register(MyImageCodecClass))`. Or to use it as a decorator:
```
@fabio.register
class MyImageCodecClass(FabioImage):
pass
```
Close #177
> Move codec registry from FabioImage class to fabioformat

- fabio/edfimage.py
- fabio/test/testedfimage.py
This PR proposes to add a `fabio.edfimage.edf_lazy_iterator` function that returns an iterator over the frames of a single multi-frame EDF file.
The benefit is to avoid reading the whole file to get the number of frames and build the index before doing anything.
> EDF multi-frame iterator

- fabio/edfimage.py
Clean up the EDF compression parsing
- Fix test (warn only if there is NO compression)
- Log as warning, not info
@diorcety i reuse your patch on EDF file reader. Let me know if you still have problems
> Fix EDF compression warning

- fabio/dm3image.py
A report (and suggested fix) came in from G. Mangan, about dm3image failing when only a single 'Binning' item was present in the file. This fix allows either one or two numbers. Also a small cleanup.
> fixes to dm3image

- fabio/edfimage.py
- fabio/fabioimage.py
- fabio/fabioutils.py
- fabio/utils/deprecation.py
- version.py
This PR plan the deprecation warnings for fabio 0.10.0beta, while allowing to display pending deprecation warning if requested.
```
import fabio
image = fabio.open("../data/edf/medipix.edf")
image.getData()
```
```
import logging
logging.getLogger("fabio.DEPRECATION").setLevel(logging.DEBUG)
import fabio
image = fabio.open("../data/edf/medipix.edf")
image.getData()
DEBUG:fabio.DEPRECATION:Function getData is deprecated. Reason: Prefer using 'img.data'.
File "<ipython-input-5-94eb0a625094>", line 1, in <module>
image.getData()
```
> Deprecation for 0.10.0

- fabio/eigerimage.py
- fabio/hdf5image.py
HDF5 file was not closed when the FabioImage was not anymore needed.
This should improve the things especially on Windows.
> Close HDF5 from fabio image

- fabio/numpyimage.py
This PR makes `fabio` tests pass with `numpy` 1.16.3.
The issue is due to a change of default value of the `allow_pickle` argument of `numpy.load` from True to False due to security issue.
This fix just set `allow_pickle` to True... which makes a security vulnerability (see https://github.com/numpy/numpy/blob/master/numpy/lib/npyio.py#L316)
closes #313
> Fix change of default for numpy.load allow_pickle arg

- fabio/edfimage.py
- fabio/test/codecs/test_edfimage.py
This branch was remaining in my workspace.
It was from a previous feed back from P. Boesecke.
- Use `blobsize` instead of `size`
- Size is reserved for the decompressed size
- Add tests on `Sphere2Saxs` data output
> Robustness on EDF

- fabio/pixiimage.py
This PR changes the way pixiimage file series filename is split to work even with more than on `$` in the filename.
> Makes filename series split with $ in the name

- fabio/edfimage.py
- fabio/test/codecs/__init__.py
- fabio/test/codecs/test_edfimage1.py
Reading edf files, without assuming all restrictions of the "Klora" convention. It prepares the possibility of using a general header (see http://wikiserv.esrf.fr/bliss/index.php/ESRF_Data_Format). The following bug has been removed: A header end pattern that is split across read buffers is recognized. A test has been added (EdfBlockBoundaryCases in test_edfimage1.py). Apart from the bug-fix there no additional features have been added. All existing edf-files should be readable as before, probably with updated messages.
> Reading edf files, without all restrictions of the "Klora" convention.

- MANIFEST.in
This PR adds `packaging/debian10` to the source tarball.
> Also include debian10 packaging files in sdist

- build-deb.sh
This PR synchronizes `build-deb.sh` script with that of silx.
Beyond tab/whitespace, it uses `python3` instead of `python` and replaces:
`dch --bpo "${project} snapshot ${version} built for ${target_system}"`
with
`dch -D ${debian_name}-backports -l~bpo${debian_version}+ "${project} snapshot ${version} built for ${target_system}"`
> Update build deb

- fabio/edfimage.py
Presumably a windows thing - it takes 50 ms to run this tostring line for a 2048x2048 image
Issue noticed on python3.7 64 bits and windows 10.
> Do not create a temporary string (it slows down writing on windows)

- fabio/edfimage.py
- fabio/test/codecs/test_edfimage1.py
The Global Header Section (general block) is the one that starts with the keyword EDF_DataFormatVersion, otherwise no Global Header Section is defined for the opened file. Its contents is used as default for all frames. Checks have been added in test_edfimage1.py for verifying the correct reading of these type of files and for verifying that a keyword of the general block is really used as default in data frame headers.
(originally, "VersionNumber" was defined for this purpose. Because it could be located somewhere inside the header it would require reading the full header. This is time consuming and has been abandoned.)
> Recognizing a Global Header Section and using it as default

- fabio/edfimage.py
A problem has been fixed that could only arise when reading edf files with extremely short (less than 512 bytes) header sections, e.g. an extremely short global header followed by an empty binary data block.
> Cleaning edf header block reading

- fabio/edfimage.py
- fabio/openimage.py
- fabio/test/codecs/test_edfimage1.py
With these commits fabio (edfimage.py) should be in the state of reading frames from all edf files created at ESRF/ID01 and ESRF/ID02 during the last 15 years.
> Reading binary data from files and tests

- fabio/openimage.py
This PR make the EDF magic readable.
As result, we can easily see that there is dup:
- b"\n{\r\nEDF" is already triggered by b"\n{"
- b"{\r\nEDF" is already triggered by b"{"
- b"{\n"  is already triggered by b"{"
- b"\n{\n",'edf') is already triggered by b"\n{"
I let you see what to do with this information.
> Make EDF magic it readable

- fabio/numpyimage.py
The NumpyImage class writes the data in its dataset attribute to the file rather than using its data attribute which is used by the conversion function of FabioImage. The NumpyImage writes the data attribute to the file (which is None in that case) and creates a pickeled file without the actual data in it.
> fixed issue #316 and issue #313

- fabio/mar345image.py
I did not find the extension for the mar555 detector.
> Provide all the default file extension for mar345

- CHANGELOG.rst
- version.py
This PR adds a `CHANGELOG.rst` file and bump the version to `0.10.0` in order to prepare a release of `fabio`.
> Add changelog and prepare a release

- fabio/openimage.py
- fabio/test/test_fabio.py
The `_openimage` was never tested.
There is a regression in 0.10, so it was not possible to read `BytesIO` with `fabio.open`.
This is only a fix which could be part to a bug fix.
The `_openimage` should be reworked. This code is reading twice the streams (read the full data for the magic, then read again the full data to parse the stream). This should be avoided, if you deal will standard compressed streams, it's just not efficient, and maybe buggy.
> Fix BytesIO

- setup.py
To avoid any confusion, let's state it clearly and prevent Python2 from installing fabio 0.11
close #379 
@jonwright, is this OK for you ?
> Declare only python3 comparibility

- fabio/edfimage.py
- fabio/test/codecs/test_edfimage.py
This PR is a clean up of #376 from @jonwright 
- warning message in case of non-ascii char in the header (in this case the key-value is drop)
- warning on duplicated key (same behavior as before, the previous key is drop)
- debug message on header line without = (not a key-value)
- i think it would be definitely better to log it as warning
Closes #373
> Robustness on EDF header

- fabio/fabioimage.py
Here is a PR to fix #384
Considering this API was not used (cause there was this exception) i would prefer to alias if to `frames` instead of using the iteration through filenames.
```
def __iter__(self):
for frame in self.frames():
yield frame
```
What do you think?
> Remove the raise at the end of the iteration

- fabio/fabioimage.py
- fabio/test/test_fabio_image.py
This PR add a test for `FabioImage.__iter__`.
That's a backport from the backport to 0.10.
> Add test for FabioImage __iter__

- fabio/fabioimage.py
- fabio/hdf5image.py
- fabio/test/codecs/test_hdf5image.py
This PR implements the `next` function to HDF5 frames.
Limitation: As the link between frame to container is a weakref, the reference to the fabioimage have to be referenced by the user.
Closes #397
> Implement and test hdf5format 'next' function

- fabio/TiffIO.py
Palette color images are identical to monochrome images but must have interpretation set to 3.
closes #405
> Ignore colormap when not matching interpretation

- fabio/cbfimage.py
I believe these lines have no purpose anymore and just clutter the output.
> cleanup leftover print() commands from cbfimage.py

- fabio/mrcimage.py
- fabio/test/codecs/test_mrcimage.py
> fix MRC fileformat

- README.rst
Fix #455 
- Changed order of sections to put forward **Installation**, **Usage** and **Documentation**
- Updated **Usage** examples
- Added a table of contents
- Reformulated **Transparent handling of compressed files** section (was really hard to understand). Please review to see if the sense is still correct.
- **Installation** and **Changelog** links point now to the online doc
I left **Design Specifications** untouched but in my opinion, it should be in the online doc and not in the README.
> Change README section order and reformulate some paragraphs

- fabio/openimage.py
Add magic number to support [big tiff](https://www.awaresystems.be/imaging/tiff/bigtiff.html). Normally only the version number has to be changed (42 to 43).
This is far from being perfect, not sure how it should be done. With this change, fabio is able to fall-back on `PIL` and read the data (and so `silx view` works on these kind of files).
> Add support for "Big tiff"

- fabio/HiPiCimage.py
The assumption that data from HiPic is 12 bit data so if values are able 4095 it is a BG corrected image and these values should be negative, has been removed.
> 12 bit data is no longer assumed 

- .github/workflows/python-package.yml
- fabio/TiffIO.py
> [IO] Ignore photometric interpretation if not supported.

- src/fabio/GEimage.py
- src/fabio/openimage.py
- src/fabio/test/codecs/test_geimage.py
This file type started coming from APS in ~2022 with a `.edf.ge5` extension.
In fabio, these were being interpreted as EDF files because of their EDF-like header. With the changes in this PR, the file is interpreted as a GE file instead and the frames are read in correctly.
The added logic is as follows:
1. If the file is identified as EDF, we check the file extension, and if the file extension is `ge` plus a number, it is interpreted as GE instead.
2. We check for EDF header formats in the GE reader, and if we have a match, we read in the header using EDF style and grab the number of frames from there.
I have an ~80 MB dark example... let me see if we can make that public for testing.
Fixes: #553
> Add support for GE files with an EDF header

- src/fabio/ext/dense.pyx
- src/fabio/sparseimage.py
@jonwright  can you provide one of your sparse file generated at ID11 to check if it is compatible
@marcocamma same for you at ID10.
> Support for sparse frames without background (XPCS among other)

- .github/workflows/release.yml
- doc/source/conf.py
- pyproject.toml
- requirements.txt
This PR adds a release workflow that is triggered when publishing a release in github and that can be run manually.
This workflow:
- Builds and tests the source tarball
- Builds and tests the wheels with cibuildwheel
- Builds the documentation and saves it as a zip file
- Publishes the tarball and wheels in pypi when the workflow is triggered by a published release (and after validation)
To make it work it requires to:
This is adapted from cibuildwheel documentation:
- [Configure a CI service](https://cibuildwheel.pypa.io/en/stable/setup/#github-actions)
- [Deliver to pypi](https://cibuildwheel.pypa.io/en/stable/deliver-to-pypi/#github-actions)
It's similar to [silx's release.yml](https://github.com/silx-kit/silx/blob/main/.github/workflows/release.yml) and [hdf5plugin's …
> CI: Added github action release workflow

- src/fabio/fabioformats.py
- src/fabio/lambdaimage.py
- src/fabio/meson.build
- src/fabio/openimage.py
- src/fabio/test/codecs/__init__.py
- src/fabio/test/codecs/meson.build
- src/fabio/test/codecs/test_lambdaimage.py
- version.py
> Support reading for lambda-detector Nexus files

- build-deb.sh
- src/fabio/binaryimage.py
- src/fabio/compression/agi_bitfield.py
- src/fabio/dm3image.py
- src/fabio/ext/src/columnfile.c
- src/fabio/fit2dmaskimage.py
- src/fabio/pixiimage.py
- src/fabio/test/codecs/test_binaryimage.py
- src/fabio/test/test_fabio_image.py
> Issues spotted by debian report

- src/fabio/edfimage.py
- src/fabio/fabioimage.py
- src/fabio/test/codecs/test_edfimage.py
- src/fabio/test/codecs/test_edfimage_expg.py
close #578
Nice catch by the way !
> Fix `fast_read_data` when reading the last line

- src/fabio/app/eiger2crysalis.py
- version.py
> Implement Eiger2Crysalis with Eiger master file
