silx-kit/fabio

- fabio-src/pilatusimage.py
> FIX: Issue with str functions and Python 3 on PilatusImage class

- fabio/TiffIO.py
> Add 0 padding if the data is smaller than the expected size (close #72)

- doc/source/install.rst
> Fix doc. Thanks to Yves

- fabio/fabioimage.py
- fabio/fabioutils.py
> pretty print the header.

- fabio/edfimage.py
- fabio/fabioimage.py
> Add list of reserver header keys

- fabio/xsdimage.py
- Use the standard library if it is available
- Fix deprecated syntax and function name
Closes #130
> Robustness on xml library

- fabio/bruker100image.py
- fabio/fabioformats.py
- fabio/fabioimage.py
- fabio/jpegimage.py
- fabio/openimage.py
- fabio/test/test_all.py
- fabio/test/testfabioimage.py
- fabio/test/testjpegimage.py
- fabio/tifimage.py
- fabio/utils/pilutils.py
> Support JPEG format

- fabio/fabioformats.py
- fabio/fabioimage.py
- fabio/mpaimage.py
- fabio/templateimage.py
- fabio/test/test_all.py
- fabio/test/testmpaimage.py
Added the ability to read in multiwire (.mpa) files.
It's a clean version of the pull request https://github.com/silx-kit/fabio/pull/139.
>  Added ability to read multiwire (.mpa) files (cleaned up)

- build-deb8.sh
- doc/html/_sources/install.txt
- doc/source/install.rst
- package/debian8/control
- package/debian8/rules
- package/debian9/control
- package/debian9/rules
It contains fabio viewer and fabio convert packages
Closes #136
> Create fabio-bin debian package

- build-deb.sh
- package/debian8/control
- package/debian9/control
- setup.py
Backport some tools from silx + enhancements
> packaging for ubuntu/arm64

- fabio/app/_matplotlib.py
- package/debian9/control
- setup.py
Correct a few errors in packaging, an import error in the binary as well
> App and packaging

- fabio/test/utilstest.py
> Clean up file io using with

- fabio/test/testfabioconvert.py
- Clean up stderr which was still displayed
- All to display no script output, script output only if error (-v) always the script output (-vv)
> Clean up test logging

- fabio/TiffIO.py
- fabio/test/test_all.py
- fabio/test/test_image_convert.py
- fabio/tifimage.py
> Fix convert edf to tiff

- fabio/openimage.py
This PR rework the way filenames are parsed.
- First it check if the filename is an openned stream (and not a string)
- Then check if the filename exists in the filesystem
- And finally parse it as an URL
Some  cases are still not taken into account (`toto#foo::bar`), but URL or `::` or `ByteIO` are i guess not used with fabio?
Closes #212
> Check first if the file exists

- fabio/fabioimage.py
- fabio/fabioutils.py
- fabio/openimage.py
- fabio/test/testfabioimage.py
Here is a path to support `pathlib`.
I am not very happy with it code the architecture do not have a good file abstraction, with a lot of API, then there is a lot of duplication. But it is working.
Let me know if it is useful.
The "Clean up tests" commit is a random clean up which have no relation with this PR. It can be part of another PR if you prefer.
Closes #215
> Support pathlib

- fabio/GEimage.py
- fabio/HiPiCimage.py
- fabio/OXDimage.py
- fabio/TiffIO.py
- fabio/adscimage.py
- fabio/binaryimage.py
- fabio/bruker100image.py
- fabio/brukerimage.py
- fabio/compression.py
- fabio/dm3image.py
- fabio/edfimage.py
- fabio/fit2dimage.py
- fabio/fit2dmaskimage.py
- fabio/kcdimage.py
- fabio/mrcimage.py
- fabio/pixiimage.py
- fabio/pnmimage.py
- fabio/raxisimage.py
- fabio/readbytestream.py
- fabio/tifimage.py
- fabio/utils/pilutils.py
- fabio/xsdimage.py
Copy data only if they may be modified
byteswap them in place where-ever possible
Remove commented-out code (if 0)
> Use numpy.frombuffer

- fabio/TiffIO.py
- fabio/test/testtifimage.py
- fabio/tifimage.py
- fabio/utils/pilutils.py
- Fix TiffIO (the patch is not ready, check it with @vasole)
- Fix PIL fallback to use the `P` mode (palette), the general case is i guess more complex, but it is already fine.
The result is a 3 dim image (width, height, channel)
Closes #232
> Fix TIFF image using RGB LUT

- fabio/pilatusimage.py
> fix regex regression in Python 3.7 (2)

- doc/source/getting_started.rst
- fabio/fabioformats.py
- fabio/mrcimage.py
- fabio/test/test_all.py
- fabio/test/testmrcimage.py
Still work in progress - test missing
> mrc format

- fabio/HiPiCimage.py
> Fix python header

- fabio/edfimage.py
Previous size was limited to 512 x 20 bytes (why?), new 512 x 40
> fix header size for edf files.

- fabio/edfimage.py
- fabio/test/testedfimage.py
Fix regression on test and doc
> Fix lazy tests

- fabio/jpeg2kimage.py
- fabio/test/testjpeg2kimage.py
- Clean up log
- Robustness of PIL and glymur versions on Debian 7
> Improve jpg2k support

- build-deb.sh
Just installed debian10 for some tests ... everything works so far
> compatibility with debian10 ... just debian9+ right now

- ci/requirements_travis.txt
lxml do not support anymore python 3.3
> Fix python 3.3

- setup.py
> close #288

- setup.py
> revert back sys.path list

- fabio/adscimage.py
- fabio/openimage.py
Here is small typo to clean up to provide better debug message, and a better ADSC reader.
> Improve adsc format

- setup.py
This PR synchronizes the setup.py with the current one from silx.
In particular:
- `sdist` now build the cythonized files
- the extra compile args are compatible with numpy 1.16
- The symbols are hidden with manylinux wheels
- The `numpy` version is was compiled with is advertise as a minimum required version
- `cython` is no more in `setup_requires` (we could argue about that...)
> Synchronize setup.py with that of silx

- ci/appveyor.yml
> Upgrade AppVeyor from Python 3.4->3.7

- README.rst
I tried the previous solution (fabio.edfimage()) and it was not working. I have updated it from the documentation found in the fabio.edfimage module.
> Fix edfimage example

- fabio/tifimage.py
close #312 
all test are passing now
> polish tif via pillow

- ci/requirements_travis.txt
For keeping compatibility with Debian8/Python3.4
> Conditional dependencies in the requirement.txt file

- fabio/OXDimage.py
- fabio/__init__.py
- fabio/bruker100image.py
- fabio/jpeg2kimage.py
> fix minor issues spotted from LGTM

- .gitignore
- fabio/compression/__init__.py
- fabio/compression/agi_bitfield.py
- fabio/compression/compression.py
- fabio/compression/setup.py
- fabio/esperantoimage.py
- fabio/fabioformats.py
- fabio/openimage.py
- fabio/test/codecs/__init__.py
- fabio/test/codecs/test_esperantoimage.py
- fabio/test/test_agi_bitfield.py
- fabio/test/test_all.py
adds support for esperanto files. Testing and test data as well as documentation are needed.
> add support for esperanto files (issue #346)

- fabio/OXDimage.py
- fabio/TiffIO.py
- fabio/app/viewer.py
- fabio/binaryimage.py
- fabio/bruker100image.py
- fabio/brukerimage.py
- fabio/compression/compression.py
- fabio/dtrekimage.py
- fabio/edfimage.py
- fabio/fabioutils.py
- fabio/fit2dmaskimage.py
- fabio/mar345image.py
- fabio/mrcimage.py
- fabio/openimage.py
- fabio/pnmimage.py
- fabio/test/codecs/test_brukerimage.py
- fabio/test/codecs/test_edfimage.py
- fabio/test/codecs/test_mccdimage.py
- fabio/test/test_flat_binary.py
- fabio/test/testfilenames.py
- fabio/utils/pilutils.py
- version.py
remove future deprecation warning of numpy
> use numpy.tobytes where needed

- doc/source/coverage.rst
- version.py
> Final update of the coverage for v0.10

- fabio/openimage.py
> mistake tobytes vs tostring

- fabio/openimage.py
- fabio/test/testfilenames.py
I will try to push this to v0.10 branch as I assume I pushed to master and that was wrong. My apologies for being rather bad at git.
> testcase for FilenameObjects

- fabio/compression/compression.py
- setup.py
Ensure man pages are correct
close #366
close #367 
@picca is this OK for you ?
> 366 debian patches

- doc/source/Changelog.rst
- fabio/edfimage.py
- fabio/fabioimage.py
- fabio/fabioutils.py
- fabio/openimage.py
- fabio/test/codecs/test_edfimage.py
- fabio/test/test_fabio.py
- fabio/test/testfabioimage.py
- fabio/test/testfilenames.py
- version.py
Here is the bug fix for the branch 0.10. For the version 0.10.2.
Changelog and version was updated.
I have tested it manually on Python 2.7 and Python 3.8.
@kif it is ready to merge.
> Backport master to 0.10

- setup.py
> Backport changes from silx & pyFAI

- .travis.yml
- ci/appveyor.yml
- fabio/app/eiger2cbf.py
- fabio/cbfimage.py
- setup.py
Implement a converter to CBF from out Eiger files
> Parser for Pilatus specific headers

- version.py
> increment development version

- fabio/fabioutils.py
> Compatibility for python 3.5-3.9

- build-deb.sh
- fabio/app/eiger2crysalis.py
- fabio/compression/agi_bitfield.py
- fabio/esperantoimage.py
- fabio/ext/_agi_bitfield.pyx
- fabio/ext/setup.py
- fabio/test/codecs/test_esperantoimage.py
- fabio/test/test_agi_bitfield.py
- run_tests.py
- setup.py
The constrain about size in the range 256-4096 is not
yet enforced ...
Eiger 16Mpix detector is larger than the 4096² shall we crope?
> Esperanto format reading and writing

- ci/appveyor.yml
- doc/source/Changelog.rst
> Drop win32, test python3.9

- fabio/app/eiger2crysalis.py
- fabio/esperantoimage.py
> Export esperanto

- .github/workflows/python-package.yml
- ci/requirements_gh.txt
> Github action CI

- fabio/OXDimage.py
- fabio/TiffIO.py
- fabio/ext/mar345_IO.pyx
- fabio/ext/src/ccp4_pack.c
- fabio/fabioimage.py
- fabio/speimage.py
- fabio/test/codecs/test_xsdimage.py
Fix plenty of deprecation warnings
> Deprecation

- bootstrap.py
- fabio/TiffIO.py
- fabio/app/_qt.py
- setup.py
Fabio did not use anymore six, now sieve out `sys.version` based tests
> remove test if python2 or 3

- fabio/jpeg2kimage.py
> address newer version of Glymur

- fabio/bruker100image.py
- fabio/test/codecs/test_bruker100image.py
The idea is to separate the codec from the I/O
The reading part is already in a separated function, the writing is still TODO.
This is a pre-requist for  #433
> Clean up bruker100

- fabio/bruker100image.py
- fabio/test/codecs/test_bruker100image.py
I will better refactor Bruker100 before finishing this PR ...
close #401
> 401 convert bruker100

- fabio/sparseimage.py
This applies also for the first image!
close #436
> define a flat at the class level to tell if images should have noise

- fabio/app/eiger2crysalis.py
By default, the mask is not calculated and this option
triggers the calculation (no extra parameter).
> Make --calc-mask opt-in

- fabio/fabioimage.py
- fabio/test/codecs/test_hdf5image.py
and prevent regression with a test !
> close #441

- ci/requirements_appveyor.txt
- ci/requirements_gh.txt
- ci/requirements_rtd.txt
- ci/requirements_travis.txt
- fabio/ext/dense.pyx
- requirements.txt
> security warninigs in GH dependencies

- fabio/limaimage.py
- fabio/nexus.py
- fabio/test/test_nexus.py
This PR contains the modification made on limaimage to write stacks of images
Related to #443
> 443 limaimage

- fabio/eigerimage.py
- fabio/fabioimage.py
This is a simple patch to allow easier writing of HDF5 files with the Eiger-style
Related to #443
> eiger format writing

- fabio/edfimage.py
- fabio/test/codecs/test_edfimage.py
- fabio/test/testutils.py
> 459 dim issue

- fabio/app/densify.py
in case the wavelenght is missing...
> handle case where wavelength is unknown

- fabio/fabioutils.py
- fabio/test/test_io_limits.py
> FileI0.read and FileIO.write have a limit in size for a single operation

- fabio/ext/dense.pyx
- fabio/sparseimage.py
- fabio/test/test_densification.py
> Fix noisy test

- fabio/eigerimage.py
- fabio/test/codecs/test_eigerimage.py
> 479 eigerimage

- fabio/app/viewer.py
> progressBar.setValue takes integers as input

- .github/workflows/python-package.yml
- fabio/TiffIO.py
- fabio/test/codecs/test_jpeg2kimage.py
- fabio/test/codecs/test_tifimage.py
close #502
Integrate Armando's patch
> regression test

- bootstrap.py
minor improvement in developer tools
> Improvement in the local install lib.

- fabio/test/codecs/__init__.py
- fabio/test/codecs/meson.build
- fabio/test/codecs/test_hipicimage.py
> Test for the reading of the HiPiC format

- src/fabio/_version.py
- src/fabio/cbfimage.py
- src/fabio/test/codecs/test_cbfimage.py
> 535 cbf header

- pyproject.toml
- src/fabio/_version.py
> Decalre all dependencies needed to run tests in `pyproject.toml`

- src/fabio/compression/compression.py
To be validated (I don't have access to such computers)
@picca can you run the test on the S390 ? thanks for the report.
> This should fix the decoding of CBF files on big-endian computer.

- doc/source/conf.py
> fix documentation build

- build-deb.sh
> Fix debian packaging

- src/fabio/OXDimage.py
- src/fabio/test/codecs/test_esperantoimage.py
> fix numpy2 compatibility

- src/fabio/app/densify.py
- src/fabio/app/eiger2crysalis.py
> removes _version

- ci/requirements_gh.txt
- pyproject.toml
- src/fabio/app/hdf2neggia.py
- src/fabio/app/meson.build
> New application to convert HDF5 files into the `neggia` format used by XDS for example (MX data)

- .readthedocs.yaml
- src/fabio/app/densify.py
- src/fabio/esperantoimage.py
- src/fabio/fabioformats.py
- src/fabio/sparseimage.py
- src/fabio/test/test_formats.py
> Fix extention manipulation

- src/fabio/app/densify.py
- src/fabio/ext/dense.pyx
- src/fabio/sparseimage.py
- src/fabio/test/test_densification.py
- version.py
> link peaks from sparse to dense file

- .gitattributes
> clean sdist from sandbox & CI files

- src/fabio/ext/dense.pyx
- src/fabio/sparseimage.py
Correct the way rounding is performed.
To be discussed with Tamas if the clipping of values makes sense ...
> Densify proper rounding
